import 'dart:typed_data';
import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../models/transaction.dart';

Future<Uint8List> buildTransactionPdf(TransactionModel tx) async {
  final doc = pw.Document();
  final isIncome = tx.type == TransactionType.income;
  final amountFmt = NumberFormat.currency(symbol: '₦', decimalDigits: 2);
  final dateFmt = DateFormat('EEE, dd MMM yyyy hh:mm a');

  final earningsOrSpending = tx.amount;
  final total = isIncome ? (tx.amount - tx.fee) : (tx.amount + tx.fee);

  doc.addPage(
    pw.Page(
      pageFormat: PdfPageFormat.a4,
      build: (context) {
        return pw.Container(
          padding: const pw.EdgeInsets.all(24),
          child: pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text('Expense Logger Receipt',
                  style: pw.TextStyle(
                    fontSize: 22,
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColors.blue700,
                  )),
              pw.SizedBox(height: 8),
              pw.Text('Transaction ID: ${tx.id}', style: const pw.TextStyle(fontSize: 10)),
              pw.Divider(),

              pw.SizedBox(height: 12),
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text('Type', style: pw.TextStyle(color: PdfColors.grey700)),
                      pw.Text(isIncome ? 'Income' : 'Expense',
                          style: pw.TextStyle(
                            fontSize: 16,
                            fontWeight: pw.FontWeight.bold,
                            color: isIncome ? PdfColors.green600 : PdfColors.red600,
                          )),
                    ],
                  ),
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.end,
                    children: [
                      pw.Text('Amount', style: pw.TextStyle(color: PdfColors.grey700)),
                      pw.Text(amountFmt.format(tx.amount),
                          style: pw.TextStyle(
                            fontSize: 20,
                            fontWeight: pw.FontWeight.bold,
                          )),
                    ],
                  ),
                ],
              ),

              pw.SizedBox(height: 16),
              pw.Container(
                decoration: pw.BoxDecoration(
                  color: PdfColors.blue50,
                  borderRadius: pw.BorderRadius.circular(8),
                ),
                padding: const pw.EdgeInsets.all(12),
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text('Details', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                    pw.SizedBox(height: 6),
                    pw.Text('Category: ${tx.category}'),
                    pw.Text('From/To: ${tx.counterparty ?? '-'}'),
                    pw.Text('Date & Time: ${dateFmt.format(tx.dateTime)}'),
                    if ((tx.notes ?? '').isNotEmpty) pw.Text('Notes: ${tx.notes}'),
                  ],
                ),
              ),

              pw.SizedBox(height: 16),
              pw.Text('Breakdown', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
              pw.SizedBox(height: 8),
              pw.Container(
                decoration: pw.BoxDecoration(
                  border: pw.Border.all(color: PdfColors.grey300),
                  borderRadius: pw.BorderRadius.circular(8),
                ),
                padding: const pw.EdgeInsets.all(12),
                child: pw.Column(
                  children: [
                    _row('Earnings/Spending', amountFmt.format(earningsOrSpending)),
                    _row('Fee', amountFmt.format(tx.fee)),
                    pw.Divider(),
                    _row('Total', amountFmt.format(total), bold: true),
                  ],
                ),
              ),

              pw.Spacer(),
              pw.Align(
                alignment: pw.Alignment.center,
                child: pw.Text('Generated by Expense Logger',
                    style: pw.TextStyle(color: PdfColors.grey600, fontSize: 10)),
              ),
            ],
          ),
        );
      },
    ),
  );

  return doc.save();
}

pw.Widget _row(String label, String value, {bool bold = false}) {
  return pw.Padding(
    padding: const pw.EdgeInsets.symmetric(vertical: 4),
    child: pw.Row(
      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
      children: [
        pw.Text(label, style: pw.TextStyle(fontWeight: bold ? pw.FontWeight.bold : pw.FontWeight.normal)),
        pw.Text(value, style: pw.TextStyle(fontWeight: bold ? pw.FontWeight.bold : pw.FontWeight.normal)),
      ],
    ),
  );
}

